In [1]:
import numpy as np
import os
import sys
from ipycanvas import MultiCanvas, hold_canvas
from IPython.display import display, HTML
from scipy.spatial.distance import cdist
from sklearn.utils import check_random_state
sys.path.append(os.path.abspath('../'))
from antfarm import Brownian, Gravity, Vicsek
from antfarm.base import AntFarm
from antfarm.utils.data import make_grid
from antfarm.utils.sugar import attrmethod, buildmethod

In [177]:
class Gravity(AntFarm):
    @attrmethod
    def __init__(self, n_ants=100, drift=0., gravity=.1, friction=.1, **kwargs):
        super().__init__(n_ants, **kwargs)

        self.v = self._state.normal(0., drift, size=(n_ants, 2))
        self.a = np.zeros((n_ants, 2))
        self.a[:, 1] = gravity

    def _check_walls(self):
        for ax in (0, 1):
            lower = (x := self.x[:, ax]) < self.ant_size
            upper = x > (wall := self.shape[ax] - self.ant_size)
            self.v[lower | upper, ax] *= -1.*(1. - self.friction)
            self.x[lower, ax], self.x[upper, ax] = self.ant_size, wall

    def _check_edges(self):
        edges = ((d := cdist(self.x, self.x)) > 0.) & (d < 2.*self.ant_size)
        edges += (~(edges.max(1)))*np.eye(self.n_ants, dtype=np.bool)
        x_, v_ = self.x[mask := edges.argmax(1)], self.v[mask]
        n = np.max((np.linalg.norm(dx := self.x - x_), 1.))**2
        self.v -= ((self.v - v_)*dx).sum(1)[:, None]*dx/n
        # self.x += 2.*np.diag(~edges)*(self.step_rate*self.v + (self.step_rate**2)*self.a/2)
        # x_update = (edges*(~np.eye(self.n_ants, dtype=np.bool))*(self.ant_size - d/2)).max(1)/np.sqrt(1 + (self.v[:, 1]/self.v[:, 0])**2)*self.v[:, 0]
        # y_update = (edges*(~np.eye(self.n_ants, dtype=np.bool))*(self.ant_size - d/2)).max(1)/np.sqrt(1 + (self.v[:, 0]/self.v[:, 1])**2)*self.v[:, 1]
        # self.x[:, 0] += x_update
        # self.x[:, 1] += y_update

    def _step(self):
        self.v += self.step_rate*self.a
        self.x += self.step_rate*self.v + (self.step_rate**2)*self.a/2
        self._check_walls()
        self._check_edges()

model = Gravity(10, drift=1., ant_size=20)
model.start()

MultiCanvas(width=500)

Button(description='Start', style=ButtonStyle())

In [55]:
15. - (hood*d).max(1)

array([ 4.70436986,  4.70436986, 15.        ])

In [60]:
(edges*(15. - d)).max(1)

array([ 4.70436986,  4.70436986, 15.        ])

In [75]:
x

array([[10., 15.],
       [19., 20.],
       [30.,  5.]], dtype=float32)

In [160]:
x = np.array([[10, 15], [19, 20], [30, 5]], dtype=np.float32)
v = np.array([[2, -1], [-3, -1], [4, 1]], dtype=np.float32)

edges = ((d := cdist(x, x)) > 0.) & (d < 15.)
edges += (~(edges.max(1)))*np.eye(x.shape[0], dtype=np.bool)
x_, v_ = x[mask := edges.argmax(1)], v[mask]
n = np.max((np.linalg.norm(dx := x - x_), 1.))**2
v -= ((v - v_)*dx).sum(1)[:, None]*dx/n
v /= v.sum(1)[:, None]
# x += (v*(edges*(~np.eye(3, dtype=np.bool))*(15. - d)).max(1)[:, None])
x

array([[10., 15.],
       [19., 20.],
       [30.,  5.]], dtype=float32)

In [161]:
v

array([[-0.04545454,  1.0454545 ],
       [ 1.059633  , -0.05963303],
       [ 0.8       ,  0.2       ]], dtype=float32)

In [162]:
x_update = (edges*(~np.eye(3, dtype=np.bool))*(15. - d/2)).max(1)/np.sqrt(1 + (v[:, 1]/v[:, 0])**2)*v[:, 0]
y_update = (edges*(~np.eye(3, dtype=np.bool))*(15. - d/2)).max(1)/np.sqrt(1 + (v[:, 0]/v[:, 1])**2)*v[:, 1]

In [163]:
np.sqrt(x_update**2 + y_update**2)

array([10.29030789, 10.42326044,  0.        ])

In [164]:
x_update

array([-0.01945234, 10.42320816,  0.        ])

In [165]:
y_update

array([10.29028951, -0.03301142,  0.        ])

In [166]:
x[:, 0] += x_update
x[:, 1] += y_update

In [167]:
x

array([[ 9.980548, 25.290289],
       [29.423208, 19.96699 ],
       [30.      ,  5.      ]], dtype=float32)

In [168]:
cdist(x, x)

array([[ 0.        , 20.15823795, 28.50393459],
       [20.15823795,  0.        , 14.97809948],
       [28.50393459, 14.97809948,  0.        ]])